spring:
  application:
    name: zmh_config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonedaniel/springcloud_demo
          search-paths:
server:
  port: 9010