spring:
  application:
    name: zmh_config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonedaniel/openconfig.git
          search-paths: zmh_config_repo
          username: ${git_username}
          password: ${git_password}
server:
  port: 9010